name: Java Format
on: [push]
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Add google-java-format plugin to pom.xml
        run: |
          echo '<build><plugins><plugin><groupId>com.github.siom79</groupId><artifactId>fmt-maven-plugin</artifactId><version>2.10</version><configuration><style>google</style></configuration></plugin></plugins></build>' > temp_pom.xml
          cat pom.xml >> temp_pom.xml
          mv temp_pom.xml pom.xml
      - name: Format Java code
        run: mvn fmt:format
      - name: Commit formatted code
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Apply google-java-format" || true
          git push
